### ISSUE TITLE
Build a pipeline to download data from PubMed

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/pubmed-dl#1]
## Description 

Build a pipeline to download data from PubMed. 
// Fill in detail - What is the goal of this issue? How will this information be used?

### Details

- Fields to include
  - PMID
  - Title
  - Abstract   
  - Other: May need other fields initially to filter on (e.g. PublicationType)

### Tasks
  - [x] Create separate remote on GitHub for this capability (https://github.com/PathwayCommons/pubmed-dl)
  - [x] Port over code for `ncbi.py` from semantic-search
  - [x] Copy over `.env` file (imported through dotenv package in `ncbi.py`)
  - [x] Familiarize with code in `ncbi.py` 
    - Consider: Scaling: current code may be limiting (e.g. streaming, chunking)
    - e.g. > 10^6 records
  - [x] Test if you can write out a subset of data to file, check data integrity    
  - [x] Stats: Time, memory, errors
  - [ ] Declare package dependencies required

### Notes
- Considerations
  - How long does it take to download?
  - How long does it take to index?
  - How much memory is used in indexing?

Supercedes https://github.com/PathwayCommons/semantic-search/issues/43

**Comment by JohnGiorgi** [comment]
@Anwesh1

```python
print("Hello world")
```

```json
{"test": "Hello World"}
```

Click edit to see the raw text.

**Comment by Anwesh1** [comment]
I have branched (Anwesh1-PMID/abstract-1) the primary program that gets the data from PubMed (based on given dates) and two types of files it returns. The .json files are retrieved from PubMed while the .txt file is a summary of all the records in the PMID, abstract format. requests_test.py -> program 
pubmed_batch_20000_to_29999.json ->  data from Pubmed 
pubmed_batch_20000_to_29999_abstracts.txt -> relevant data (PMID, abstract), each line is a separate record

**Comment by jvwong** [comment]
I added a task `Declare package dependencies required` -  @JohnGiorgi  probably knows better how to do this...setup.py? @Anwesh1 maybe look at the semantic search to see how it handles this.

**Comment by JohnGiorgi** [comment]
@Anwesh1 Checkout the [`setup.py`](https://github.com/PathwayCommons/semantic-search/blob/master/setup.py) file, along with the [install instructions in the README](https://github.com/PathwayCommons/semantic-search#installation). You can copy these and modify them as needed. Also, remember that any directory you want to consider a python module (e.g. you want to be able to import from it) should contain a `__init__.py` file (it can be empty). Again take a look at [semantic search](https://github.com/PathwayCommons/semantic-search/tree/master/semantic_search).

Let me know if you get stuck!

**Comment by Anwesh1** [comment]
> @Anwesh1 Checkout the [`setup.py`](https://github.com/PathwayCommons/semantic-search/blob/master/setup.py) file, along with the [install instructions in the README](https://github.com/PathwayCommons/semantic-search#installation). You can copy these and modify them as needed. Also, remember that any directory you want to consider a python module (e.g. you want to be able to import from it) should contain a `__init__.py` file (it can be empty). Again take a look at [semantic search](https://github.com/PathwayCommons/semantic-search/tree/master/semantic_search).
> 
> Let me know if you get stuck!

Hey @JohnGiorgi, I'm not exactly sure how this installation stuff works but is it very similar to what you have on the ```semantic-search```? In the ```README.md``` installation paragraph to be precise. Also for the ```setup.py``` should I follow the same format as what you did on your ```setup.py```?

**Comment by JohnGiorgi** [comment]
@Anwesh1 I can set it up if you are not familiar with python packaging and `setuptools`. It will likely take me a couple of days to get to it

**Comment by Anwesh1** [comment]
@JohnGiorgi oh okay that would be great. I was honestly just copying what you had on the ```semantic-search```. I will create a PR with this file and also add the ```__init__.py`` so when we merge it should be easier.

**Comment by JohnGiorgi** [comment]
Sorry, I meant that I take care of updating the readme and adding a `setup.py` as well as formatting this as a proper python package. No need to open a PR on your end

**Comment by Anwesh1** [comment]
oh sorry, I made one...but I have deleted it. Thanks

**Comment by JohnGiorgi** [comment]
Done (#6).

**Comment by Anwesh1** [comment]
Thanks @JohnGiorgi !!! I will act like I understand what you did 😆
